### ISSUE TITLE
Mac OS executable in assets for v0.4.1 is still 0.4.0

### ISSUE THREAD

**Issue by otherjoel** [Chleba/netscanner#14]
The [`netscanner-mac.tar.gz`](https://github.com/Chleba/netscanner/releases/download/v0.4.1/netscanner-mac.tar.gz) link in https://github.com/Chleba/netscanner/releases/tag/v0.4.1 still contains the executable for 0.4.0.

**Comment by Chleba** [comment]
Oh, I am really sorry for that and Thank You very much for a pointing that out. I will fix it ASAP.
Also I'm gonna put `netscanner` into a homebrew so I will let You know when that happened and put instructions into a README.
Thanks again.

**Comment by Chleba** [comment]
It should be fixed now. Please try it again and let me know. Thanks :)

**Comment by otherjoel** [comment]
Looks good, thanks!
