### ISSUE TITLE
[Feature request] Automatically detect the NIC's network IP address at startup and bring it to the "Discovery" field.

### ISSUE THREAD

**Issue by rizzini** [Chleba/netscanner#17]
Pretty much the title. It's a small improvement, I know, but it'd be nice for convenience.

**Comment by Chleba** [comment]
Hi,
Yes - you're right, that would be much better and I will try to put it into a next version.
Thank You.

**Comment by Chleba** [comment]
Hi,
Here is an implementation of getting prefilled input value with a subnet from the active interface - https://github.com/Chleba/netscanner/commit/226d0c6c803827c8794603d284cc3b479d4b3e89.
It will be present in the next version (0.4.2)
