### ISSUE TITLE
OS Error 1

### ISSUE THREAD

**Issue by AyaanMAG** [Chleba/netscanner#18]
I installed netscanner with cargo and there were no errors, I'm using a raspberry pi (ARM) running debian 12  and upon trying to run netscanner I'm faced with

`❯ netscanner
netscanner failed with Error:
Unable to create datalink channel: Operation not permitted (os error 1)`

**Comment by K0ntact** [comment]
Did you tried to run it with `sudo`?

**Comment by Chleba** [comment]
Hi,
As @K0ntact mention - did you try run it with `sudo` please ? That should help. If not - please let me know.
Btw. I have to try it run on RPi with debian also, just for curiosity :)
Thanks

**Comment by AyaanMAG** [comment]
@K0ntact @Chleba Yes it worked when running with sudo, i too ran this on a raspberry pi and by default i wasn't able to run this with sudo and was faced with no not found error, however setting an alias to the location of the file ~/.cargo/netscanner I was able to run it fine. Thank you for the solution @K0ntact

**Comment by minhtrancccp** [comment]
it would be great if the error suggested running with sudo instead, so that others don't have to dig through the repo for the answer

**Comment by Chleba** [comment]
@minhtrancccp Good idea - I will try to implement some info into a panic message.
