### ISSUE TITLE
Prevent scanning immediately upon starting `netscanner`

### ISSUE THREAD

**Issue by ndom91** [Chleba/netscanner#21]
Is there maybe a config value I'm missing? I didn't find a cli flag.

Anyway, when I start `netscanner`, it immediately starts scanning a subnet that's unreachable from my local LAN `192.168.1.0/24` and it doesn't seem like `ESC` can interrupt it. So basically I always have to wait for it to finish scanning that `/24` before I can doa nythign else.

Anyway to not auto-scan when starting the application?

**Comment by Chleba** [comment]
Hi,
Version `v0.4.2` will get a subnet from the active interface, so it will start scanning a range that should be valid, but you're right. It should not start scanning right after the start.
Please let me know if new version (v0.4.2) is better for You or You'll wait for next version that may have implemented features like stop scanning with `ESC` or `s` key. OR not start scanning at all.

**Comment by Chleba** [comment]
Hi,
https://github.com/Chleba/netscanner/commit/0e31b84e87997cef3181ec55d995cdb7e56c2da8 - fix is here.
The next version will have implemented start & pause packet dumping. That is also not ideal.
Automatic WiFi scanning will always be active. This App was based on this feature from the start :).

**Comment by ndom91** [comment]
Awesome, thanks a lot for the quick turn-around! :heart:
