### ISSUE TITLE
Crash Report 0.4.2 - (IPv6 only interface)

### ISSUE THREAD

**Issue by DominicOrsi** [Chleba/netscanner#22]
Attached is the crash report for v0.4.2
[report-fa0ce441-aa45-493c-a35d-04926470b508.toml.txt](https://github.com/Chleba/netscanner/files/15017859/report-fa0ce441-aa45-493c-a35d-04926470b508.toml.txt)

**Comment by Chleba** [comment]
```
"name" = "netscanner"
"operating_system" = "Mac OS 14.4.1 [64-bit]"
"crate_version" = "0.4.2"
"explanation" = """
Panic occurred in file '/Users/dominicorsi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/netscanner-0.4.2/src/components/discovery.rs' at line 553
"""
"cause" = "index out of bounds: the len is 1 but the index is 1"
"method" = "Panic"
"backtrace" = """

   0: 0x1032efa5c - core::panicking::panic_fmt::hb4d79f470bcac176
   1: 0x1032efbfc - core::panicking::panic_bounds_check::hbe0606b3c45f99d7
   2: 0x102fc0b80 - <netscanner::components::discovery::Discovery as netscanner::components::Component>::update::h220f740f03a29f09
   3: 0x102fb72b0 - netscanner::main::{{closure}}::h79db477646598b3e
   4: 0x102fb0954 - tokio::runtime::park::CachedParkThread::block_on::h30ccfdfbaa105834
   5: 0x102fc8fd4 - tokio::runtime::context::runtime::enter_runtime::h89acd54955ae5236
   6: 0x102fdf5b0 - tokio::runtime::runtime::Runtime::block_on::hc1e4b938b1d5e1ee
   7: 0x102faa4c8 - netscanner::main::h0bc9094782be655d
   8: 0x102fed0b4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hce38ae2d573b0431
   9: 0x102fcfdf0 - std::rt::lang_start::{{closure}}::h26f6b47aa5740db0
  10: 0x10329885c - std::rt::lang_start_internal::h7f00bef3cf1b3caa
  11: 0x102faa5b4 - _main"""
```
just posting error report log for others to see that may identify same bug

**Comment by Chleba** [comment]
Question please - do you have an interface without IPv4 ?
That looks like your active interface that have been found and selected as active is not have valid IPv4 and me stupidly enough did not implement any verification/check.
Sorry about that - will fix it asap.
Thanks for the report.

**Comment by DominicOrsi** [comment]
I do have an interface that is active that doesn't have an IPv4 interface which is awdl0. 
Is there a way to see which interface netscanner chooses to use when it starts?

```shell
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 1c:57:dc:31:03:e5
	inet6 2601:602:c900:8620::19a prefixlen 64 dynamic
	inet6 fe80::1804:d967:1cff:cebd%en0 prefixlen 64 secured scopeid 0xc
	inet 10.0.0.225 netmask 0xffffff00 broadcast 10.0.0.255
	inet6 2601:602:c900:8620:181d:9f2b:1766:8765 prefixlen 64 autoconf secured
	inet6 2601:602:c900:8620:35cb:c5ac:a9f0:2811 prefixlen 64 autoconf temporary
	inet6 2601:602:c900:8620::b98d prefixlen 64 dynamic
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
awdl0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether c2:dd:35:53:5b:b9
	inet6 fe80::c0dd:35ff:fe53:5bb9%awdl0 prefixlen 64 scopeid 0xd
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

**Comment by Chleba** [comment]
I may need to add an options as flags ... unfortunately not at the moment. It just take first active from the list. IPv6 handling (at least dumping packet logs) is done from 50%. I do not have IPv6 scanning implemented yet.
You may either wait for next version or turn off interface without IPv4 when starting `netscanner`; after that you may switch active interface with the `f` key.

**Comment by DominicOrsi** [comment]
Okay, 0.4.1 worked fine for me, but I am not sure if the interface that is only IPv6 is new to my device or not.

**Comment by Chleba** [comment]
Can you please verify that version `v0.4.1` have `awdl0` as active interface or `en0`?
Version `v04.2` is trying to get input value pre-filled with subnet from active interface.
Since I can't see IPv4 on any of your interfaces, there is the problem. I am parsing ipv6 as ipv4 address.
Fix will be asap.

**Comment by Chleba** [comment]
Btw. We may find a bug in `pnet` library. In theory, you should not be able to scan anything since first version that had implemented IP scanning.
You may see here that when getting vector of active interfaces, there is a condition that we get only interfaces that have IPv4 address.
https://github.com/Chleba/netscanner/blob/6089d59c1bcd0c0cb94adcaa59217ffd979bf2f5/src/components/interfaces.rs#L48

**Comment by Chleba** [comment]
https://github.com/Chleba/netscanner/commit/0e31b84e87997cef3181ec55d995cdb7e56c2da8 - fix is here.
Please confirm that the new version is working for you.
IPv6 scan support will come when I have more time for it.

**Comment by DominicOrsi** [comment]
Attached is my screenshot of having ```en0``` active but I also have ```en18```. I didn't realize this at the time but I am connected via an ethernet cable using ```en18```. By having myself hardwired ```v0.4.1``` works just fine. When I unplugged and switched to Wi-Fi I got a crash as well with ```v0.4.1```. I was on Wi-Fi when ```v0.4.2``` crashed.

<img width="1546" alt="Screenshot 2024-04-17 at 6 54 11 PM" src="https://github.com/Chleba/netscanner/assets/73092665/722965c6-72cb-4ea4-9fc4-c1fb97c70520">

Active interfaces when hardwired
```shell
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether <REDACTED>
	inet6 2601:602:c900:8620::19a prefixlen 64 dynamic
	inet6 fe80::1804:d967:1cff:cebd%en0 prefixlen 64 secured scopeid 0xc
	inet <REDACTED> netmask 0xfffffe00 broadcast 147.222.241.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
awdl0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether <REDACTED>
	inet6 fe80::a44f:bbff:fe19:d30b%awdl0 prefixlen 64 scopeid 0xd
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en18: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
        ether <REDACTED>
	inet6 fe80::1072:9131:85fa:b8de%en18 prefixlen 64 secured scopeid 0x1a
	inet <REDACTED> netmask 0xfffffe00 broadcast 147.222.163.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
```

**Comment by Chleba** [comment]
Could you please get me the crash log output from the `v0.4.1` as well please?
That needs to be something else.

**Comment by Chleba** [comment]
Hi @DominicOrsi,
I just want to verify if a new version `v0.4.3` is at least working / don't panicking and scanning and packetdumping is also not causing any issues ?

**Comment by DominicOrsi** [comment]
Everything works on v0.4.3! Thanks for rolling out such a fast fix!

**Comment by Chleba** [comment]
Thank You. I'm closing this issue. The next proper fix is implementing IPv6 support for scanning and packet dump.
