### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by Chleba** [Chleba/netscanner#29]
Hi,
I'm looking for a `Debian` package maintainer. It should be pretty simple but due to my small amount of spare time, I would like to have someone that would do that instead of me.
There is cargo helper `cargo-deb` here: https://crates.io/crates/cargo-deb that should help with packaging `netscanner` and a tutorial on how to make a package for a Debian is here: https://wiki.debian.org/HowToPackageForDebian
It would be much appreciated if someone would take this task under his/her wing.

Thanks a lot.

**Comment by DominicOrsi** [comment]
Hi @Chleba,

I will work on getting a Debian package for netscanner since I have a bit of free time. I have done a deb package before for a Rust program but nothing as complex as netscanner. I'll report back in the next few days with updates a progress.

**Comment by Chleba** [comment]
Hi @DominicOrsi,
That is wonderful news. Thank You so much that You're putting Your valuable time into this. Let me know if I could help You with anything.

**Comment by Chleba** [comment]
@DominicOrsi btw. recently Kali Linux adopt `netscanner` and because it's based on Debian You may use something from it ... maybe? Here is some commits: https://gitlab.com/kalilinux/packages/netscanner/-/commits/kali/master

**Comment by DominicOrsi** [comment]
I'll take a look at the Kali release and see what I can use from there. Thanks for showing me this!

**Comment by DominicOrsi** [comment]
Hey @Chleba 

How are you wanting the Debian package to be released. As a PPA or just a .deb package that someone can download then install?


Been looking at both options and curious what route you would like to do?

**Comment by Chleba** [comment]
I'm an old Debian guy but I haven't used it for more than a decade now so I am inclined to `*.deb` but I will completely leave that to You as a maintainer. You have my complete trust in this matter. Thank You.

**Comment by DominicOrsi** [comment]
Sounds good, I'll work on getting one up and running. Hopefully it can just be a GitHub workflow.

**Comment by DominicOrsi** [comment]
Hopefully will have a PR for `.deb` package by tonight. GitHub actions have me going :thinking:

**Comment by Chleba** [comment]
Amazing. Thank You so much for that. Will you share a link for a PR and github action code? I would really love to see that and learn from it something new.

**Comment by DominicOrsi** [comment]
How do you update the release tag at the moment? Is it manually changing it in `Cargo.toml` i.e. `0.5.1` to `0.5.2`?

**Comment by DominicOrsi** [comment]
> Amazing. Thank You so much for that. Will you share a link for a PR and github action code? I would really love to see that and learn from it something new.

Yes, I will. I have a fork of the repo that I am testing everything with. You can see the [GitHub action](https://github.com/DominicOrsi/netscanner/blob/main/.github/workflows/rust.yml). It is almost done, I had to create a new GitHub action to create the deb package with GitHub actions. Was a fun side quest.

**Comment by Chleba** [comment]
> How do you update the release tag at the moment? Is it manually changing it in Cargo.toml i.e. 0.5.1 to 0.5.2?

Yes

**Comment by Chleba** [comment]
> Yes, I will. I have a fork of the repo that I am testing everything with. You can see the [GitHub action](https://github.com/DominicOrsi/netscanner/blob/main/.github/workflows/rust.yml). It is almost done, I had to create a new GitHub action to create the deb package with GitHub actions. Was a fun side quest.

That's great :). Thanks again. Learning something new every day is fun, right ? :)

**Comment by DominicOrsi** [comment]
It is, was great dive into GitHub actions and docker containers in GitHub actions.

**Comment by Chleba** [comment]
Yea - docker is just great. I love it. I also have to take a look at you debian packager: https://github.com/DominicOrsi/cargo-deb-ubuntu.

**Comment by Chleba** [comment]
Closing this Issue with PR #33 merged.
Awesome work @DominicOrsi :1st_place_medal:
