### ISSUE TITLE
`Cargo.lock` vendoring

### ISSUE THREAD

**Issue by isabelroses** [Chleba/netscanner#30]
Is it possible to get a v0.5.1 release with the fixed `Cargo.lock` from this commit https://github.com/Chleba/netscanner/commit/64888667f092dd452d774082ac4058bbd06f6adb.

**Comment by Chleba** [comment]
Hi @isabelroses,
I know I messed up and I'm sorry about that. Just finishing one feature and I will release v0.5.1 with fixed `Cargo.lock`.
So sorry again I'll try to push it over tonight.

**Comment by Chleba** [comment]
Hi @isabelroses,
A new version has been [published](https://github.com/Chleba/netscanner/releases/tag/v0.5.1) with a fixed `Cargo.lock` file.
Thanks.

**Comment by isabelroses** [comment]
Thanks for this.
