### ISSUE TITLE
Feature Request: Export Discovered Devices to CSV

### ISSUE THREAD

**Issue by johnclearyconsulting** [Chleba/netscanner#32]
Hi there,

I love this app so far! I’ve successfully built it on Ubuntu and it’s working great.

Wondering if there’s any way to export or save the discovered devices to CSV? I frequently go to a site and run a scan of the network and then want to reference MACS, IPs, Hostnames, Ventors etc. later. Is this possible? 🤔

Thanks!
John

**Comment by Chleba** [comment]
Hi John,
Thank You so much. There may be soon some *.deb official release.
About exporting data to some format, that should not be a problem and I was thinking about that from the start but forgot about it.
I'll take a look at it but unfortunately I can't right now. I need to do some work at different project for next 2.weeks, but after that I'll start work at it, ok ? :)

**Comment by Chleba** [comment]
Hi @johnclearyconsulting,
Here: https://github.com/Chleba/netscanner/commit/170dd9adcb345430c6967a0784e42afd917e448c is early version of data export implementation. If You would like to try it for yourself.
Now only linux OS is supported and data is stored in the user  `$HOME` directory if you have set permissions for netscanner under your user.
If You are using netscanner as sudoer I'll take $SUDO_USER and still export data into your user home directory.
If you really are `root` then it's still remains in $HOME dir.
For now i'm exporting only `scanned_ips` & `scanned_ports` in csv format with header.

> **data is stored in $HOME/.netscanner/*.csv**

Exporting packets will take more time becase every logs types are different.

**Comment by Chleba** [comment]
Hi @johnclearyconsulting,
Here: https://github.com/Chleba/netscanner/releases/tag/v0.5.2 is the newest version of `netscanner` that have exporting data implemented.
Have fun :)
