### ISSUE TITLE
macOS airport removed

### ISSUE THREAD

**Issue by Chleba** [Chleba/netscanner#34]
Because of macOS Sonoma 14.4 removed `airport` utility `netscanner` for macOS lost it's support of scanning WiFi networks and their signal strength.
I'm looking for alternatives to use for macOS, but unfortunately suggested `wdutil` do not support scanning (or at least I don't see that anywhere).
If anyone know what to use in macOS, please let me know.
Thanks

**Comment by VladislavGatsenko** [comment]
I was looking for a solution to a different problem, but maybe this will help with a solution. Just execute in the console:

system_profiler SPAirPortDataType

**Comment by Chleba** [comment]
Fixed here: https://github.com/mic90/tokio-wifiscanner/pull/5 and published on crates.io.

**Comment by Chleba** [comment]
btw. @VladislavGatsenko man I totally forgot of Your comment and I spend so much time trying to use CoreWLAN with objc-rust bindings to make that shit work but all I did at the end is doing exactly what You commented.
I feel so stupid forgot on something like that.
You are savior but for a idiot man - sorry for this took that long and thanks again.
