### ISSUE TITLE
Graph not showing on macOS

### ISSUE THREAD

**Issue by adriangalilea** [Chleba/netscanner#40]
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/abcd8019-e8c4-4ad5-b558-6ce5dbbb51f7">

<img width="716" alt="image" src="https://github.com/user-attachments/assets/69cc54fa-626f-410d-b4bd-60abf7247a50">

Just installed this, looks great, unfortunately installed  it primarily to inspect signal strength and that specific feature does not work for me, I see no errors, simply graph won't show.

**Comment by adriangalilea** [comment]
Hey @Chleba,

I simply wanted to report the issue,

This is a free open-source project, you do not need to ask for my patience, in any case I should thank you for having shared your work and having the intentions to fix it at all :)

I also figured a way to solve my need temporarily so I'm covered. Will check your fix whenever it comes, no hurries, no worries ;)

**Comment by Chleba** [comment]
Thanks :) I'm glad you like it.
I will let you know here when this Issue will be fixed.

**Comment by Chleba** [comment]
Hi @adriangalilea,
There's a new version published - v0.6.1, where scanning wifi networks on macOS is fixed. Give it a try and let me know if something is not working properly again.
Thanks for Your report and have a great day :)
