### ISSUE TITLE
interface switching limited

### ISSUE THREAD

**Issue by rbomze** [Chleba/netscanner#44]
Latest version 0.6.1 introducing commit 0b1d76e5bcdc8f869f8bb63191a5f0feae355900 breaks interface switching partially. see comment:

> Limits possible active interfaces too strictly. Breaks the use of networks with private addresses like:
> 
> - 172.16.0.0/12
> 
> - 10.0.0.0/8
> 
> Causes potential false positive for networks with address like 192.5.x.x (outside of 192.168.0.0/16 range).
> 
>  

 _Originally posted by @rbomze in [0b1d76e](https://github.com/Chleba/netscanner/commit/0b1d76e5bcdc8f869f8bb63191a5f0feae355900#r149780005)_

**Comment by Chleba** [comment]
True - Thanks for pointing that out. I will fix that asap.

**Comment by rbomze** [comment]
Checking Ipv6Addr with is_global() might be a better approach.
https://doc.rust-lang.org/nightly/core/net/struct.Ipv4Addr.html#method.is_global

**Comment by EphemeralSapient** [comment]
Ah, I didn't notice it; I should have checked its methods before going with the least efficient way

@Chleba If possible I would like to clean up my mess :P 

I have created PR for both readme update for windows and interface thing 

And thank you for pointing out my rookie mistake

**Comment by Chleba** [comment]
Tested and merged. @rbomze please let me know if you run into another issue and thanks to let us know.
Also kudos to @EphemeralSapient for his PR.
