### ISSUE TITLE
crash: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by glitsj16** [Chleba/netscanner#6]
Hi, I noticed this package entering the AUR and gave it a try. I needed to change from stable to nightly channel to build [netscanner](https://aur.archlinux.org/packages/netscanner). Obviously nothing needed changing using the [netscanner-bin](https://aur.archlinux.org/packages/netscanner-bin) package.

But on both the app crashes with the below report:

<details>
<summary> $ cat netscanner.crash.report </summary>

```
"name" = "netscanner"
"operating_system" = "Arch Linux Rolling Release [64-bit]"
"crate_version" = "0.4.0"
"explanation" = """
Panic occurred in file 'src/components/interfaces.rs' at line 103
"""
"cause" = "called `Option::unwrap()` on a `None` value"
"method" = "Panic"
"backtrace" = """

   0: 0x5b9aca5ac5f3 - <unresolved>
   1: 0x5b9aca5ac486 - <unresolved>
   2: 0x5b9aca718517 - <unresolved>
   3: 0x5b9aca71928e - <unresolved>
   4: 0x5b9aca73660f - <unresolved>
   5: 0x5b9aca732eaf - <unresolved>
   6: 0x5b9aca6b7a0d - <unresolved>
   7: 0x5b9aca6b8e4f - <unresolved>
   8: 0x5b9aca6bad6d - <unresolved>
   9: 0x5b9aca6b2ef8 - <unresolved>
  10: 0x5b9aca6b2638 - <unresolved>
  11: 0x5b9aca6b2a6a - <unresolved>
  12: 0x5b9aca7a1666 - <unresolved>
  13: 0x5b9aca7a0bda - <unresolved>
  14: 0x5b9aca8222b1 - <unresolved>
  15: 0x5b9aca7b99a8 - <unresolved>
  16: 0x5b9aca851644 - <unresolved>
  17: 0x5b9aca851593 - <unresolved>
  18: 0x5b9aca8518e2 - <unresolved>
  19: 0x5b9acbd57791 - <unresolved>
  20: 0x5b9aca8518b6 - <unresolved>
  21: 0x5b9aca7b726d - <unresolved>
  22: 0x7b6d8c4bbcd0 - <unresolved>
  23: 0x7b6d8c4bbd8a - __libc_start_main
  24: 0x5b9aca5acd85 - <unresolved>
  25:        0x0 - <unresolved>"""

```

</details>

Hope you can figure out what went wrong. Feel free to ping if I can present anything else that can help debugging. I use [iwd](https://archlinux.org/packages/extra/x86_64/iwd/) BTW.

**Comment by Chleba** [comment]
Hi, Thank You for opening this Issue.
`netscanner` is using external third-party applications for getting WiFi information. For Linux `iw` and for MacOS `airport`.
I will try to implement a parsing case for `iwd` but now you may try to make an alias for `iwd` to `iw`. That may help for now.
In the future, I will make better parsing and handling errors from parsing those outputs. In the next version of course.

**Comment by Chleba** [comment]
Added a fix for handling unwrapping parsed values for interfaces in this commit - https://github.com/Chleba/netscanner/commit/cd1f1f3ddce9fd1bcc00e7edaa37106a3e4a1021. Hopefully, that will help.

**Comment by glitsj16** [comment]
> try to make an alias for iwd to iw

iw is already present on Arch Linux:

```sh
$ pacman -Q iw
iw 6.7-1
```

It's [this](https://archlinux.org/packages/core/x86_64/iw/) package from the core repo.

FYI, I've build from git and netscanner still crashed with the exact same report... Thanks for looking into it though!

**Comment by orhun** [comment]
> In that case the AUR packages need to add iw to the depends() array...

Done!
